name: 🐞 Bug
description: File a bug/issue
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: music-metadata version
      description: The version of music-metadata which you found the bug in
    validations:
      required: false
  - type: dropdown
    attributes:
      label: JavaScript module eco system
      description: Note that music-metadata switch to pure ESM in version 8!
      multiple: false
      options:
        - CommonJS modules (CJS)
        - ECMAScript modules (ESM)
      validations:
        required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
