name: 🐞 Bug
description: File a bug/issue
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: music-metadata version
      description: The version of music-metadata which you found the bug in
    validations:
      required: false
  - type: dropdown
    attributes:
      label: JavaScript module eco system
      description: Note that music-metadata switch to pure ESM in version 8!
      multiple: false
      options:
        - CommonJS modules (CJS), music-medata ≤ version 7
        - ECMAScript modules (ESM), music-medata ≥ version 8
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Attached audio sample?
      description: Most bugs require an audio sample to reproduce the issue. This can be zipped, and uploaded to the issue. Please try to make the sample file as small as possible. If your sample really cannot be shared you may send it by e-mail to the {repository owner}@xs4all.nl.
      options:
        - label: I have provided sufficient information to reproduce the issue
          required: true
